Update Jenkinsfile-third

diff --git a/jenkins/lab5/Jenkinsfile-third b/jenkins/lab5/Jenkinsfile-third
--- a/jenkins/lab5/Jenkinsfile-third
+++ b/jenkins/lab5/Jenkinsfile-third
@@ -1,7 +1,7 @@
 pipeline {
     agent { label 'jenkins-slave' }
     environment {
-        DOCKER_IMAGE = 'docker.io/ahmedmaher07/ivolve:v6'
+        DOCKER_IMAGE = 'docker.io/ahmedmaher07/doc:v3'
         KUBE_NAMESPACE = 'test'
         DEPLOYMENT_YAML = 'deployment.yaml'
     }
@@ -11,47 +11,52 @@ pipeline {
                 git url: 'https://github.com/wolf8534/MultiBranch.git', branch: 'third'
             }
         }
+
         stage('Build Docker Image') {
             steps {
-                sh 'docker build -t $DOCKER_IMAGE .'
-            }
-        }
-        stage('Push Docker Image') {
-            steps {
-                withCredentials([usernamePassword(credentialsId: 'Docker_hub', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
-                    sh """
-                    docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
-                    docker push $DOCKER_IMAGE
-                    """
+                script {
+                    // بناء الصورة باستخدام Docker
+                    sh 'docker build . -f Dockerfile -t docker.io/ahmedmaher07/doc:v0'
                 }
             }
         }
-        stage('Edit Deployment.yaml') {
+
+        stage('Push Docker Image') {
             steps {
-                sh "sed -i 's|image:.*|image: $DOCKER_IMAGE|g' $DEPLOYMENT_YAML"
+                script {
+                    // استخدام بيانات الاعتماد لتسجيل الدخول ودفع الصورة
+                    withCredentials([usernamePassword(credentialsId: 'Docker_hub', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
+                        sh 'docker login docker.io -u $DOCKER_USERNAME -p $DOCKER_PASSWORD'
+                        sh 'docker push docker.io/ahmedmaher07/doc:v0'
+                    }
+                }
             }
         }
+
         stage('Deploy to Kubernetes') {
             steps {
                 withCredentials([string(credentialsId: 'k8s_token', variable: 'K8S_TOKEN')]) {
                     sh """
+                    kubectl create namespace $KUBE_NAMESPACE || true
                     kubectl --kubeconfig=/home/ubuntu/jenkins/.kube/config apply -f $DEPLOYMENT_YAML -n $KUBE_NAMESPACE
                     """
                 }
             }
         }
+
         stage('Post Action') {
             steps {
                 echo "Deployment to Kubernetes completed successfully!"
             }
         }
     }
+
     post {
         success {
             echo "Pipeline executed successfully."
         }
         failure {
-            echo "Pipeline failed. Check logs for more details."
+            echo "Pipeline failed. Check the logs for errors."
         }
     }
 }
