Update Jenkinsfile-second

diff --git a/jenkins/lab5/Jenkinsfile-second b/jenkins/lab5/Jenkinsfile-second
--- a/jenkins/lab5/Jenkinsfile-second
+++ b/jenkins/lab5/Jenkinsfile-second
@@ -1,7 +1,7 @@
 pipeline {
     agent { label 'jenkins-slave' }
     environment {
-        DOCKER_IMAGE = 'docker.io/ahmedmaher07/ivolve:v9'
+        DOCKER_IMAGE = 'docker.io/ahmedmaher07/doc:v0'
         KUBE_NAMESPACE = 'dev'
         DEPLOYMENT_YAML = 'deployment.yaml'
     }
@@ -11,31 +11,52 @@ pipeline {
                 git url: 'https://github.com/wolf8534/MultiBranch.git', branch: 'second'
             }
         }
-      
+
+        stage('Build Docker Image') {
+            steps {
+                script {
+                    // بناء الصورة باستخدام Docker
+                    sh 'docker build . -f Dockerfile -t docker.io/ahmedmaher07/doc:v0'
+                }
+            }
+        }
+
+        stage('Push Docker Image') {
+            steps {
+                script {
+                    // استخدام بيانات الاعتماد لتسجيل الدخول ودفع الصورة
+                    withCredentials([usernamePassword(credentialsId: 'Docker_hub', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
+                        sh 'docker login docker.io -u $DOCKER_USERNAME -p $DOCKER_PASSWORD'
+                        sh 'docker push docker.io/ahmedmaher07/doc:v0'
+                    }
+                }
+            }
+        }
+
         stage('Deploy to Kubernetes') {
             steps {
-               
                 withCredentials([string(credentialsId: 'k8s_token', variable: 'K8S_TOKEN')]) {
                     sh """
+                    kubectl create namespace $KUBE_NAMESPACE || true
                     kubectl --kubeconfig=/home/ubuntu/jenkins/.kube/config apply -f $DEPLOYMENT_YAML -n $KUBE_NAMESPACE
                     """
                 }
             }
         }
+
         stage('Post Action') {
             steps {
-               
                 echo "Deployment to Kubernetes completed successfully!"
             }
         }
     }
+
     post {
         success {
-            
             echo "Pipeline executed successfully."
         }
         failure {
-            echo "Pipeline failed. Check the build logs for details."
+            echo "Pipeline failed. Check the logs for errors."
         }
     }
 }
